//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio_de_DBP.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IServicioG")]
    public interface IServicioG {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioG/Guardar", ReplyAction="http://tempuri.org/IServicioG/GuardarResponse")]
        void Guardar(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioG/Guardar", ReplyAction="http://tempuri.org/IServicioG/GuardarResponse")]
        System.Threading.Tasks.Task GuardarAsync(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGChannel : Laboratorio_de_DBP.ServiceReference2.IServicioG, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGClient : System.ServiceModel.ClientBase<Laboratorio_de_DBP.ServiceReference2.IServicioG>, Laboratorio_de_DBP.ServiceReference2.IServicioG {
        
        public ServicioGClient() {
        }
        
        public ServicioGClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Guardar(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento) {
            base.Channel.Guardar(nombre, apellido, correo, sexo, direccion, ciudad, requerimiento);
        }
        
        public System.Threading.Tasks.Task GuardarAsync(string nombre, string apellido, string correo, string sexo, string direccion, string ciudad, string requerimiento) {
            return base.Channel.GuardarAsync(nombre, apellido, correo, sexo, direccion, ciudad, requerimiento);
        }
    }
}
